# https://clang.llvm.org/docs/StandardCPlusPlusModules.html
# BMI: Built Module Interface

default:
	clang++ -std=c++20 -fmodule-output -fprebuilt-module-path=. hello.cppm main.cpp -o hello.exe

hello.o hello.pcm: hello.cppm
	clang++ -std=c++20 -fmodule-output -c hello.cppm

main.o: main.cpp hello.pcm
	clang++ -std=c++20 -fprebuilt-module-path=. -c main.cpp

hello.exe: main.o hello.o
	clang++ main.o hello.o -o hello.exe

clean:
	-rm  *.pcm *.o *.exe
	-del *.pcm *.o *.exe
