hello.exe: main.cpp std.o std.pcm
	$(PREFIX)clang++ -stdlib=libstdc++ -std=c++23 -fprebuilt-module-path=. main.cpp std.o -o hello.exe

std.o std.pcm:
	$(PREFIX)clang++ -stdlib=libstdc++ -std=c++23 -x c++-module -fmodule-output -c /usr/include/c++/16/bits/std.cc -Wno-reserved-module-identifier

clean:
	-rm  *.pcm *.o *.exe 2>&1 | exit
	-del *.pcm *.o *.exe 2>&1 | exit
